spring:
  profiles: default
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/turtle?allowMultiQueries=true
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
  velocity:
    charset: UTF-8
    properties.input.encoding: UTF-8
    properties.output.encoding: UTF-8 
    resourceLoaderPath: classpath:templates/
    suffix: .vm
server:
  port: 12000
  contextPath: /home/
redis.expireTime: 60
constants:
  excludeRegex: /*/statics/*|/*/main/*|/contract/list
---
spring:
  profiles: prod
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.turtlebone.top:3306/turtle?allowMultiQueries=true
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
  redis:
    database: 0
    hostName: r-wz9dbc5c7dc742e4.redis.rds.aliyuncs.com
    password: Turtle2017
    port: 6379
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: -1
  velocity:
    charset: UTF-8
    properties.input.encoding: UTF-8
    properties.output.encoding: UTF-8 
    resourceLoaderPath: classpath:templates/
    suffix: .vm
server:
  port: 12000
  contextPath: /home/
mybatis:
  mapperLocations: classpath:mapper/*.xml
redis.expireTime: 3600
constants:
  excludeRegex: /contract/list|/contract/detail|*statics*